config/routes.rb
Galparl::Application.routes.draw do
  get "pages/home"

  match '/loadcomments' => 'pages#loadcomments'
  match '/bubblechart' => 'pages#bubblechart'

  resources :word_indices

  resources :word_counts

  resources :entries

  match 'words/:id' => 'word#show'

  root :to => 'pages#home'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :body, :date, :numid, :person, :season
end

app/models/word.rb
class Word 
  # attr_accessible :count, :word, :indices, :speakers, :error
   
  def initialize(word)
    word_index = WordIndex.where(:word => word).first

    if (word_index != nil) 
        @speakers = groupBySpeakers(getEntries(word_index.indice))
        @count = WordCount.where(:word => word).first.count
        @word = word
    else 
        @error = "No results found for <i>'#{word}'</i>";
    end
  end

  def getEntries(indice)
    indice = indice.split(",")
    return Entry.find(:all, :conditions => ['numid in (?)', indice])
  end

  def groupBySpeakers(entries)
    speakers = Hash.new()
    entries.each { |entry|
        speaker = entry.person
        if (speakers.has_key?(speaker))
            bodies = speakers[speaker]
        else
            bodies = Array.new()     
        end
        bodies.push(encapsulateEntry(entry))
        speakers[speaker] = bodies
    }
    return speakers
  end

  def encapsulateEntry(entry)
    return {
        :body => entry.body,
        :date => entry.date,
        :season => entry.season,
        :numid => entry.numid
    };
  end

end

app/models/word_count.rb
class WordCount < ActiveRecord::Base
  attr_accessible :count, :word
end

app/models/word_index.rb
class WordIndex < ActiveRecord::Base
  attr_accessible :indice, :word
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.where(:numid => params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end


  def loadcomments

  end

end

app/controllers/word_controller.rb
class WordController < ApplicationController

  def show
    word = Word.new(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: word}
    end
  end

end

app/controllers/word_counts_controller.rb
class WordCountsController < ApplicationController
  # GET /word_counts
  # GET /word_counts.json
  def index
    @word_counts = WordCount.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @word_counts }
    end
  end

  # GET /word_counts/1
  # GET /word_counts/1.json
  def show
    @word_count = WordCount.where(:word => params[:id]).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word_count }
    end
  end

end

app/controllers/word_indices_controller.rb
class WordIndicesController < ApplicationController
  # GET /word_indices
  # GET /word_indices.json
  def index
    @word_indices = WordIndex.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @word_indices }
    end
  end

  # GET /word_indices/1
  # GET /word_indices/1.json
  def show
    @word_index = WordIndex.where(:word => params[:id]).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word_index }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/word_counts_helper.rb
module WordCountsHelper
end

app/helpers/word_helper.rb
module WordHelper
end

app/helpers/word_indices_helper.rb
module WordIndicesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numid %><br />
    <%= f.text_field :numid %>
  </div>
  <div class="field">
    <%= f.label :season %><br />
    <%= f.text_field :season %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :person %><br />
    <%= f.text_field :person %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <tr>
    <th>Numid</th>
    <th>Season</th>
    <th>Date</th>
    <th>Person</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.numid %></td>
    <td><%= entry.season %></td>
    <td><%= entry.date %></td>
    <td><%= entry.person %></td>
    <td><%= entry.body %></td>
    <td><%= link_to 'Show', entry %></td>
    <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
    <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Numid:</b>
  <%= @entry.numid %>
</p>

<p>
  <b>Season:</b>
  <%= @entry.season %>
</p>

<p>
  <b>Date:</b>
  <%= @entry.date %>
</p>

<p>
  <b>Person:</b>
  <%= @entry.person %>
</p>

<p>
  <b>Body:</b>
  <%= @entry.body %>
</p>


<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Galparl</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/bubblechart.html.erb
<!doctype html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Parlamento de Galicia</title>
  <meta name="description" content="Buscador de palabras das lexislaturas do parlamento de galicia">
  <meta name="author" content="Jose Juan Elosua <@jjelosua>">
  <meta name="author" content="Diego Pino García <@diepg>">

  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>

<body>

    <!-- Top menu -->
    <div>
        <div style="float: left; margin-left: 4px">
            <h1>Parlamento de Galicia</h1>

            <p style="font-size: 14px">Palabras mais pronunciadas nos diarios de sesións</p>
            <select style="float: left" id="text-select">
                <option value="4_lexislatura">4º lexislatura</option>
            </select>

            <div id="g-form-container" style="float: right">
                <form id="g-form">
                    <input type="text" name="search" placeholder="Engadir palabra" tabindex="1"><button>+</button>
                </form>
            </div>
        </div>
    </div>

    <div style="clear: both"></div>

    <!-- Bubble chart -->
    <p><div id="g-chart">
        <svg class="g-nodes" width="970" height="500"></svg>
        <div class="g-labels"></div>
    </div>
    <p>

    <div class="g-body">
        <div style="margin-left: 100px; margin-right: 100px">
            <div id="mentions-left" style="float: left; width: 450px"></div>
            <div id="mentions-right" style="float: right; width: 450px" ></div>
        </div>
    </div>

  <script type="text/javascript">
      
      $(document).ready(function() {
          var CR = 13;
            /*
          var loader = new EntryLoader($('#container'));
          var chart = new BubbleChart('#vis', loader);
          chart.init();
            */
  
          $('#word').keydown(function(e) {
              if (e.keyCode == CR) {
                var word = this.value;
                getWord(word);
                /*
                chart.findOrAddWord(word);
                renderWordEntries(word);
                clearTextbox(this);
                */
              }
  
              function renderWordEntries(word) {
                loader.renderWordEntries(word);
              }
  
              function clearTextbox(textbox) {
                textbox.value = "";
              }
          });
      });

      function getWord(word) {
        $.get('/word_counts/' + word + '.json', function(data) {
            alert(data.word);
        });
      }

  </script>

  <%= javascript_include_tag 'bubble-chart.js' %>
  
</body>
</html>

app/views/pages/graph.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Parlamento de Galicia</title>
  <meta name="description" content="Buscador de palabras de las legislaturas del parlamento de galicia">
  <meta name="author" content="Jose Juan Elosua <@jjelosua>">
  <meta name="author" content="Diego Pino García <@diepg>">

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag 'reset' %>
  <%= stylesheet_link_tag 'bootstrap.min.css' %>
  <%= stylesheet_link_tag 'style' %>
  <%= javascript_include_tag 'modernizr-2.0.6.min.js' %>
</head>

<body>

    <div id="container" class="container">

        <div style="float: right">
            <input id="word" type="text" size="32" style="padding: 3px" />
        </div>

        <select id="text-select">
            <option value="galparl">4º lexislatura</option>
        </select>

        <header>
            <h1>Parlamento de Galicia, <span id="book-title"></span></h1>
            <h2>Palabras mais pronunciadas nos diarios de sesións</h2>
        </header>

        <div id="main" role="main">
            <div id="vis"></div>
            <div id="status"></div>
            <div id="controls">
                <h3>Jitter</h3>
                <form id="jitter" oninput="output.value = (jitter_input.value / 200).toFixed(3)" >
                    <input id="jitter_input" type="range" min="0" max="400" value="100" style="width:240px;">
                    <output name="output" for="input">0.5</output>
                </form>
            </div>
        </div>
        <!--
        <footer>
            <p><a href="http://vallandingham.me/building_a_bubble_cloud.html">Blog Post</a> | <a href="https://github.com/vlandham/bubble_cloud">Source Code</a> | <a href="http://www.nytimes.com/interactive/2012/09/04/us/politics/democratic-convention-words.html">Original Inspiration</a></p>
        </footer>
        -->
    </div> 
    <!-- end of #container -->


  <!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script> -->
  <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.2.min.js"><\/script>')</script>

  <%= javascript_include_tag 'plugins' %>
  <%= javascript_include_tag 'coffee-script' %>
  <%= javascript_include_tag 'd3.v2.js' %>

  <script defer src="js/plugins.js"></script>
  <script src="js/libs/coffee-script.js"></script>
  <script src="js/libs/d3.v2.js"></script>
  <script type="text/coffeescript" src="coffee/vis.coffee"></script>

  <script> 
    window._gaq = [['_setAccount','UA-17355070-1'],['_trackPageview'],['_trackPageLoadTime']];
    Modernizr.load({
      load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
    });
  </script>


  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->
  
</body>
</html>

app/views/pages/home.html.erb
<style type="text/css">
    p.title {
        font-weight: bold;
    }

</style>

Para ir al bubblechart, pulse <a href="/bubblechart">aquí</a>

<h1>API::Diario de Sesiones del Parlamento Galicia</h1>

<ul>
    <li>
        <p class="title">GET /word_counts/:palabra:.:format:</p> 
        <p>Número de repeticiones de una palabra</p>
        <p>Formatos: <i>xml</i>, <i>json</i>
        <pre>
        $curl localhost:3000/word_counts/folga.json

        {"count":48,"created_at":"2013-03-20T16:35:45Z","id":8648,"updated_at":"2013-03-20T16:35:45Z","word":"folga"}
        </pre>
    </li>
</ul>

<ul>
    <li>
        <p class="title">GET /word_indices/:palabra:.:format:</p> 
        <p>Ids de las entradas donde aparece la palabra. El campo <i>indice</i> es una colección de referencias al campo <i>numid</i> de la tabla <i>entries</i></p>
        <p>Formatos: <i>xml</i>, <i>json</i>
        <pre>
        curl localhost:3000/word_indices/folga.json

        {"created_at":"2013-03-20T16:35:50Z","id":8648,"indice":"6915,6915,6915,6915,6915,14170,1752,1752,543,9196,1752,14150,14150,
        17499,14249,8365,7989,45,14184,14184,14184,14184,5991,17102,13941,13941,12948,3719,6437,13958,16798,262,6923,8363,7768,7768,
        97,97,4759,4527,258,258,258,13550,258,17110,919,17447","updated_at":"2013-03-20T16:35:50Z","word":"folga"}
        </pre>
    </li>
</ul>

<ul>
    <li>
        <p class="title">GET /words/:palabra:.:format:</p> 
        <p>Resumen de información sobre una palabra</p>
        <p>Formatos: <i>xml</i>, <i>json</i>
        <pre>
        curl localhost:3000/words/pokemon.json
        {"error":"No results found for <i>'pokemon'</i>"}

        curl localhost:3000/words/folga.json
        {
            "speakers": {
                "speaker 1": [entry],
                "speaker 2": [entry],
                ...
                "speaker n": [entry],
            },
            "count": number,
            "word": string
        }

        entry {
            "body": string,
            "date": date,
            "season": number,
            "numid": number
        }
        </pre>
    </li>
</ul>

app/views/pages/loadcomments.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>

<body>
    <input id="word" type="text" placeholder="Add word"/>
    <div id="container"></div>
</body>

<script type="text/javascript">
    
    $(document).ready(function() {
        var CR = 13;

        $('#word').keydown(function(e) {
            if (e.keyCode == CR) {
                renderWordEntries(this.value);
                clearTextbox(this);
            }

            function renderWordEntries(word) {
                var loader = new EntryLoader($('#container'));
                loader.renderWordEntries(word);
            }

            function clearTextbox(textbox) {
                textbox.value = "";
            }
        });
    });

</script>
</html>

app/views/word_counts/_form.html.erb
<%= form_for(@word_count) do |f| %>
  <% if @word_count.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word_count.errors.count, "error") %> prohibited this word_count from being saved:</h2>

      <ul>
      <% @word_count.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br />
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.text_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/word_counts/edit.html.erb
<h1>Editing word_count</h1>

<%= render 'form' %>

<%= link_to 'Show', @word_count %> |
<%= link_to 'Back', word_counts_path %>

app/views/word_counts/index.html.erb
<h1>Listing word_counts</h1>

<table>
  <tr>
    <th>Word</th>
    <th>Count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @word_counts.each do |word_count| %>
  <tr>
    <td><%= word_count.word %></td>
    <td><%= word_count.count %></td>
    <td><%= link_to 'Show', word_count %></td>
    <td><%= link_to 'Edit', edit_word_count_path(word_count) %></td>
    <td><%= link_to 'Destroy', word_count, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Word count', new_word_count_path %>

app/views/word_counts/new.html.erb
<h1>New word_count</h1>

<%= render 'form' %>

<%= link_to 'Back', word_counts_path %>

app/views/word_counts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Word:</b>
  <%= @word_count.word %>
</p>

<p>
  <b>Count:</b>
  <%= @word_count.count %>
</p>


<%= link_to 'Edit', edit_word_count_path(@word_count) %> |
<%= link_to 'Back', word_counts_path %>

app/views/word_indices/_form.html.erb
<%= form_for(@word_index) do |f| %>
  <% if @word_index.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word_index.errors.count, "error") %> prohibited this word_index from being saved:</h2>

      <ul>
      <% @word_index.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br />
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :indice %><br />
    <%= f.text_area :indice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/word_indices/edit.html.erb
<h1>Editing word_index</h1>

<%= render 'form' %>

<%= link_to 'Show', @word_index %> |
<%= link_to 'Back', word_indices_path %>

app/views/word_indices/index.html.erb
<h1>Listing word_indices</h1>

<table>
  <tr>
    <th>Word</th>
    <th>Indice</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @word_indices.each do |word_index| %>
  <tr>
    <td><%= word_index.word %></td>
    <td><%= word_index.indice %></td>
    <td><%= link_to 'Show', word_index %></td>
    <td><%= link_to 'Edit', edit_word_index_path(word_index) %></td>
    <td><%= link_to 'Destroy', word_index, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Word index', new_word_index_path %>

app/views/word_indices/new.html.erb
<h1>New word_index</h1>

<%= render 'form' %>

<%= link_to 'Back', word_indices_path %>

app/views/word_indices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Word:</b>
  <%= @word_index.word %>
</p>

<p>
  <b>Indice:</b>
  <%= @word_index.indice %>
</p>


<%= link_to 'Edit', edit_word_index_path(@word_index) %> |
<%= link_to 'Back', word_indices_path %>